### ISSUE TITLE
when path : 1   options.path.indexOf is not a function

### ISSUE THREAD

**Issue by xjdata** [steverydz/build-url#14] opened 2018-06-19 06:29 UTC
```js
export function update({ id, ...params }) {
  return request(buildUrl(baseUrl, { path: id }), {
    method: "PATCH",
    body: JSON.stringify(params),
  });
}
```

**Comment by steverydz** [comment] 2018-06-27 19:00
I'm not able to reproduce this given the information provided. Could you provide more context?

**Comment by arausly** [comment] 2019-02-14 13:16
`buildUrl('https://example.com',{
   queryParams:{
    redirect_url:'http://127.0.0.1/someotherurl/auth/callback',
   }
})`

`// returns  https://example.com/redirect_uri=http:%2F%2F127.0.0.1%2Fsomeotherurl%2Fauth%2Fcallback`

wasn't really expecting this. not sure if this is the original intent

**Comment by steverydz** [comment] 2019-02-14 13:59
@arausly No that's definitely not the intended behaviour. I'll look into this.

**Comment by steverydz** [comment] 2019-02-16 08:41
@arausly After looking into this I realise I misunderstood your bug. I thought you were referring to passing in `redirect_url` and getting `redirect_uri` in return but after running some tests it doesn't seem like that's the case.

If you're issue is related to the fact the URI is encoded, you can remedy this by wrapping your response in `decodeURIComponent`:

```
var myURL = buildURL('https://example.com, {
  queryParams: {
    redirect_url: 'http://127.0.0.1/someotherurl/auth/callback'
  }
});

someOtherFunctionCall(decodeURIComponent(myURL));
```

**Comment by steverydz** [comment] 2019-02-16 08:42
@xjdata Since you haven't supplied more information and I have been unable to reproduce this I am going to close this issue.

**Closed** 2019-02-16 08:43 UTC
Labels: wontfix
